<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Common Alogrithm: testing::internal::HandleExceptionsInMethodIfSupported</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Common Alogrithm
   &#160;<span id="projectnumber">0.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "../../search",false,'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('d0/da7/namespacetesting_1_1internal_addb2ed165b92b74e25fe9ebe9e46b9f9.html','../../'); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<a id="file_addb2ed165b92b74e25fe9ebe9e46b9f9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#file_addb2ed165b92b74e25fe9ebe9e46b9f9">&#9670;&nbsp;</a></span>HandleExceptionsInMethodIfSupported()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Result testing::internal::HandleExceptionsInMethodIfSupported </td>
          <td>(</td>
          <td class="paramtype">T *&#160;</td>
          <td class="paramname"><em>object</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Result(T::*)()&#160;</td>
          <td class="paramname"><em>method</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const char *&#160;</td>
          <td class="paramname"><em>location</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<div class="fragment"><div class="line"><a name="l02411"></a><span class="lineno"> 2411</span>&#160;                                                          {</div>
<div class="line"><a name="l02412"></a><span class="lineno"> 2412</span>&#160;  <span class="comment">// NOTE: The user code can affect the way in which Google Test handles</span></div>
<div class="line"><a name="l02413"></a><span class="lineno"> 2413</span>&#160;  <span class="comment">// exceptions by setting GTEST_FLAG(catch_exceptions), but only before</span></div>
<div class="line"><a name="l02414"></a><span class="lineno"> 2414</span>&#160;  <span class="comment">// RUN_ALL_TESTS() starts. It is technically possible to check the flag</span></div>
<div class="line"><a name="l02415"></a><span class="lineno"> 2415</span>&#160;  <span class="comment">// after the exception is caught and either report or re-throw the</span></div>
<div class="line"><a name="l02416"></a><span class="lineno"> 2416</span>&#160;  <span class="comment">// exception based on the flag&#39;s value:</span></div>
<div class="line"><a name="l02417"></a><span class="lineno"> 2417</span>&#160;  <span class="comment">//</span></div>
<div class="line"><a name="l02418"></a><span class="lineno"> 2418</span>&#160;  <span class="comment">// try {</span></div>
<div class="line"><a name="l02419"></a><span class="lineno"> 2419</span>&#160;  <span class="comment">//   // Perform the test method.</span></div>
<div class="line"><a name="l02420"></a><span class="lineno"> 2420</span>&#160;  <span class="comment">// } catch (...) {</span></div>
<div class="line"><a name="l02421"></a><span class="lineno"> 2421</span>&#160;  <span class="comment">//   if (GTEST_FLAG(catch_exceptions))</span></div>
<div class="line"><a name="l02422"></a><span class="lineno"> 2422</span>&#160;  <span class="comment">//     // Report the exception as failure.</span></div>
<div class="line"><a name="l02423"></a><span class="lineno"> 2423</span>&#160;  <span class="comment">//   else</span></div>
<div class="line"><a name="l02424"></a><span class="lineno"> 2424</span>&#160;  <span class="comment">//     throw;  // Re-throws the original exception.</span></div>
<div class="line"><a name="l02425"></a><span class="lineno"> 2425</span>&#160;  <span class="comment">// }</span></div>
<div class="line"><a name="l02426"></a><span class="lineno"> 2426</span>&#160;  <span class="comment">//</span></div>
<div class="line"><a name="l02427"></a><span class="lineno"> 2427</span>&#160;  <span class="comment">// However, the purpose of this flag is to allow the program to drop into</span></div>
<div class="line"><a name="l02428"></a><span class="lineno"> 2428</span>&#160;  <span class="comment">// the debugger when the exception is thrown. On most platforms, once the</span></div>
<div class="line"><a name="l02429"></a><span class="lineno"> 2429</span>&#160;  <span class="comment">// control enters the catch block, the exception origin information is</span></div>
<div class="line"><a name="l02430"></a><span class="lineno"> 2430</span>&#160;  <span class="comment">// lost and the debugger will stop the program at the point of the</span></div>
<div class="line"><a name="l02431"></a><span class="lineno"> 2431</span>&#160;  <span class="comment">// re-throw in this function -- instead of at the point of the original</span></div>
<div class="line"><a name="l02432"></a><span class="lineno"> 2432</span>&#160;  <span class="comment">// throw statement in the code under test.  For this reason, we perform</span></div>
<div class="line"><a name="l02433"></a><span class="lineno"> 2433</span>&#160;  <span class="comment">// the check early, sacrificing the ability to affect Google Test&#39;s</span></div>
<div class="line"><a name="l02434"></a><span class="lineno"> 2434</span>&#160;  <span class="comment">// exception handling in the method where the exception is thrown.</span></div>
<div class="line"><a name="l02435"></a><span class="lineno"> 2435</span>&#160;  <span class="keywordflow">if</span> (<a class="code" href="../../d0/da7/namespacetesting_1_1internal_ad104a3ca418dd1726ea22240b5d77258.html#ad104a3ca418dd1726ea22240b5d77258">internal::GetUnitTestImpl</a>()-&gt;catch_exceptions()) {</div>
<div class="line"><a name="l02436"></a><span class="lineno"> 2436</span>&#160;<span class="preprocessor">#if GTEST_HAS_EXCEPTIONS</span></div>
<div class="line"><a name="l02437"></a><span class="lineno"> 2437</span>&#160;    <span class="keywordflow">try</span> {</div>
<div class="line"><a name="l02438"></a><span class="lineno"> 2438</span>&#160;      <span class="keywordflow">return</span> <a class="code" href="../../d0/da7/namespacetesting_1_1internal_ac5293b438139ef7ed05cb7fcaaf63545.html#ac5293b438139ef7ed05cb7fcaaf63545">HandleSehExceptionsInMethodIfSupported</a>(<span class="keywordtype">object</span>, method, location);</div>
<div class="line"><a name="l02439"></a><span class="lineno"> 2439</span>&#160;    } <span class="keywordflow">catch</span> (<span class="keyword">const</span> internal::GoogleTestFailureException&amp;) {  <span class="comment">// NOLINT</span></div>
<div class="line"><a name="l02440"></a><span class="lineno"> 2440</span>&#160;      <span class="comment">// This exception type can only be thrown by a failed Google</span></div>
<div class="line"><a name="l02441"></a><span class="lineno"> 2441</span>&#160;      <span class="comment">// Test assertion with the intention of letting another testing</span></div>
<div class="line"><a name="l02442"></a><span class="lineno"> 2442</span>&#160;      <span class="comment">// framework catch it.  Therefore we just re-throw it.</span></div>
<div class="line"><a name="l02443"></a><span class="lineno"> 2443</span>&#160;      <span class="keywordflow">throw</span>;</div>
<div class="line"><a name="l02444"></a><span class="lineno"> 2444</span>&#160;    } <span class="keywordflow">catch</span> (<span class="keyword">const</span> <a class="codeRef" target="_blank" href="http://en.cppreference.com/w/cpp/error/exception.html">std::exception</a>&amp; e) {  <span class="comment">// NOLINT</span></div>
<div class="line"><a name="l02445"></a><span class="lineno"> 2445</span>&#160;      <a class="code" href="../../d0/da7/namespacetesting_1_1internal_a4fdfe94b1ad045e6e66e6227dd0d130d.html#a4fdfe94b1ad045e6e66e6227dd0d130d">internal::ReportFailureInUnknownLocation</a>(</div>
<div class="line"><a name="l02446"></a><span class="lineno"> 2446</span>&#160;          TestPartResult::kFatalFailure,</div>
<div class="line"><a name="l02447"></a><span class="lineno"> 2447</span>&#160;          FormatCxxExceptionMessage(e.<a class="codeRef" target="_blank" href="http://en.cppreference.com/w/cpp/error/exception/what.html">what</a>(), location));</div>
<div class="line"><a name="l02448"></a><span class="lineno"> 2448</span>&#160;    } <span class="keywordflow">catch</span> (...) {  <span class="comment">// NOLINT</span></div>
<div class="line"><a name="l02449"></a><span class="lineno"> 2449</span>&#160;      <a class="code" href="../../d0/da7/namespacetesting_1_1internal_a4fdfe94b1ad045e6e66e6227dd0d130d.html#a4fdfe94b1ad045e6e66e6227dd0d130d">internal::ReportFailureInUnknownLocation</a>(</div>
<div class="line"><a name="l02450"></a><span class="lineno"> 2450</span>&#160;          TestPartResult::kFatalFailure,</div>
<div class="line"><a name="l02451"></a><span class="lineno"> 2451</span>&#160;          FormatCxxExceptionMessage(NULL, location));</div>
<div class="line"><a name="l02452"></a><span class="lineno"> 2452</span>&#160;    }</div>
<div class="line"><a name="l02453"></a><span class="lineno"> 2453</span>&#160;    <span class="keywordflow">return</span> <span class="keyword">static_cast&lt;</span>Result<span class="keyword">&gt;</span>(0);</div>
<div class="line"><a name="l02454"></a><span class="lineno"> 2454</span>&#160;<span class="preprocessor">#else</span></div>
<div class="line"><a name="l02455"></a><span class="lineno"> 2455</span>&#160;    <span class="keywordflow">return</span> <a class="code" href="../../d0/da7/namespacetesting_1_1internal_ac5293b438139ef7ed05cb7fcaaf63545.html#ac5293b438139ef7ed05cb7fcaaf63545">HandleSehExceptionsInMethodIfSupported</a>(<span class="keywordtype">object</span>, method, location);</div>
<div class="line"><a name="l02456"></a><span class="lineno"> 2456</span>&#160;<span class="preprocessor">#endif  </span><span class="comment">// GTEST_HAS_EXCEPTIONS</span></div>
<div class="line"><a name="l02457"></a><span class="lineno"> 2457</span>&#160;  } <span class="keywordflow">else</span> {</div>
<div class="line"><a name="l02458"></a><span class="lineno"> 2458</span>&#160;    <span class="keywordflow">return</span> (object-&gt;*method)();</div>
<div class="line"><a name="l02459"></a><span class="lineno"> 2459</span>&#160;  }</div>
<div class="line"><a name="l02460"></a><span class="lineno"> 2460</span>&#160;}</div>
<div class="ttc" id="aexception_html"><div class="ttname"><a href="http://en.cppreference.com/w/cpp/error/exception.html">std::exception</a></div></div>
<div class="ttc" id="anamespacetesting_1_1internal_a4fdfe94b1ad045e6e66e6227dd0d130d_html_a4fdfe94b1ad045e6e66e6227dd0d130d"><div class="ttname"><a href="../../d0/da7/namespacetesting_1_1internal_a4fdfe94b1ad045e6e66e6227dd0d130d.html#a4fdfe94b1ad045e6e66e6227dd0d130d">testing::internal::ReportFailureInUnknownLocation</a></div><div class="ttdeci">void ReportFailureInUnknownLocation(TestPartResult::Type result_type, const std::string &amp;message)</div><div class="ttdef"><b>Definition:</b> gtest.cc:2250</div></div>
<div class="ttc" id="anamespacetesting_1_1internal_ac5293b438139ef7ed05cb7fcaaf63545_html_ac5293b438139ef7ed05cb7fcaaf63545"><div class="ttname"><a href="../../d0/da7/namespacetesting_1_1internal_ac5293b438139ef7ed05cb7fcaaf63545.html#ac5293b438139ef7ed05cb7fcaaf63545">testing::internal::HandleSehExceptionsInMethodIfSupported</a></div><div class="ttdeci">Result HandleSehExceptionsInMethodIfSupported(T *object, Result(T::*method)(), const char *location)</div><div class="ttdef"><b>Definition:</b> gtest.cc:2383</div></div>
<div class="ttc" id="anamespacetesting_1_1internal_ad104a3ca418dd1726ea22240b5d77258_html_ad104a3ca418dd1726ea22240b5d77258"><div class="ttname"><a href="../../d0/da7/namespacetesting_1_1internal_ad104a3ca418dd1726ea22240b5d77258.html#ad104a3ca418dd1726ea22240b5d77258">testing::internal::GetUnitTestImpl</a></div><div class="ttdeci">UnitTestImpl * GetUnitTestImpl()</div><div class="ttdef"><b>Definition:</b> gtest-internal-inl.h:927</div></div>
<div class="ttc" id="awhat_html"><div class="ttname"><a href="http://en.cppreference.com/w/cpp/error/exception/what.html">std::exception::what</a></div><div class="ttdeci">T what(T... args)</div></div>
</div><!-- fragment -->
<p class="reference">References <a class="el" href="../../#l00927">testing::internal::GetUnitTestImpl()</a>, <a class="el" href="../../#l02383">testing::internal::HandleSehExceptionsInMethodIfSupported()</a>, <a class="el" href="../../#l00054">TestPartResult::kFatalFailure</a>, <a class="el" href="../../#l02250">testing::internal::ReportFailureInUnknownLocation()</a>, and <a class="elRef" target="_blank" href="http://en.cppreference.com/w/cpp/error/exception/what.html">exception::what()</a>.</p>

<p class="reference">Referenced by <a class="el" href="../../#l02465">Test::Run()</a>, <a class="el" href="../../#l02630">TestInfo::Run()</a>, <a class="el" href="../../#l02759">TestCase::Run()</a>, and <a class="el" href="../../#l04185">UnitTest::Run()</a>.</p>
<div id="dynsection-0" onclick="return toggleVisibility(this)" class="dynheader closed" style="cursor:pointer;">
  <img id="dynsection-0-trigger" src="../../closed.png" alt="+"/> Here is the call graph for this function:</div>
<div id="dynsection-0-summary" class="dynsummary" style="display:block;">
</div>
<div id="dynsection-0-content" class="dyncontent" style="display:none;">
<div class="center"><img src="../../d0/da7/namespacetesting_1_1internal_addb2ed165b92b74e25fe9ebe9e46b9f9_addb2ed165b92b74e25fe9ebe9e46b9f9_cgraph.png" border="0" usemap="#ad0/da7/namespacetesting_1_1internal_addb2ed165b92b74e25fe9ebe9e46b9f9_addb2ed165b92b74e25fe9ebe9e46b9f9_cgraph" alt=""/></div>
<!-- MAP 0 -->
</div>
<div id="dynsection-1" onclick="return toggleVisibility(this)" class="dynheader closed" style="cursor:pointer;">
  <img id="dynsection-1-trigger" src="../../closed.png" alt="+"/> Here is the caller graph for this function:</div>
<div id="dynsection-1-summary" class="dynsummary" style="display:block;">
</div>
<div id="dynsection-1-content" class="dyncontent" style="display:none;">
<div class="center"><img src="../../d0/da7/namespacetesting_1_1internal_addb2ed165b92b74e25fe9ebe9e46b9f9_addb2ed165b92b74e25fe9ebe9e46b9f9_icgraph.png" border="0" usemap="#ad0/da7/namespacetesting_1_1internal_addb2ed165b92b74e25fe9ebe9e46b9f9_addb2ed165b92b74e25fe9ebe9e46b9f9_icgraph" alt=""/></div>
<!-- MAP 1 -->
</div>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_97aefd0d527b934f1d99a682da8fe6a9.html">lib</a></li><li class="navelem"><a class="el" href="../../dir_3fc1520d95d269c1cc96c54f57f8da6b.html">googletest</a></li><li class="navelem"><a class="el" href="../../dir_413744d01ad3bfc6a23a3cf4ea72332c.html">src</a></li><li class="navelem"><a class="el" href="../../df/d5b/gtest_8cc.html">gtest.cc</a></li>
    <li class="footer">Generated by <a href="https://www.doxygen.org/index.html"><img class="footer" src="../../doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1 </li>
  </ul>
</div>
</body>
</html>
